baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Something"
isCJKLanguage = true
languageCode = "zh-CN"

theme = "demo-theme"

GoogleAnalytics = "UA-79264835-1"
DisqusShortname = "keelii-blog"

[permalinks]
    archives = "/:year/:month/:day/:filename/"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    Name = "Blog"
    URL = "/"
    weight = 1

[[menu.main]]
    Name = "Archives"
    URL = "/archives"
    weight = 2


[[menu.main]]
    Name = "About"
    URL = "/about"
    weight = 3

[params]
    author = "keelii"
    description  = "There's always __ you do not know yet"
    htmlLang = "zh-CN"
    searchUrl = "https://www.google.com/search"

    pageScripts = [
        "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.7.0/highlight.min.js",
        "/javascripts/octopress.js",
        "/javascripts/post.js",
    ]
    pageStyles = [
        "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.7.0/styles/solarized-dark.min.css"
    ]

    scripts = [
        "//cdn.bootcss.com/jquery/1.9.1/jquery.min.js",
        "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"
    ]
    styles = [
        "//fonts.lug.ustc.edu.cn/css?family=PT+Serif:regular,italic,bold,bolditalic",
        "//fonts.lug.ustc.edu.cn/css?family=PT+Sans:regular,italic,bold,bolditalic"
    ]

[params.sidebar]
    recent = true
    recentCount = 5

    category = true


