name = "octo-enhance"
license = "MIT"
licenselink = ""
description = "none"
homepage = "https://keelii.com/"
tags = ["octopress"]
min_version = 0.17

[author]
  name = "keelii"
  homepage = "https://keelii.com/"